#!/bin/bash

not_correct=true
while $not_correct
do
  echo "Container id (DEFAULT: 412):"
  read VHSM_CNT
  if [ ! $VHSM_CNT ]; then
    VHSM_CNT=412  
  fi
  if [ $VHSM_CNT -gt 99 ]; then
    not_correct=false
  else
    echo "Incorrect container id"
  fi
done

not_correct=true
while $not_correct
do
  echo "Path to openvz containers (DEFAULT: /var/lib/vz/private/):"
  read VHSM_CNT_DIR
  if [ ! "$VHSM_CNT_DIR" ]; then
    VHSM_CNT_DIR="/var/lib/vz/private/"
  fi
  if [ -d $VHSM_CNT_DIR ]; then
    not_correct=false
  else
    echo "Incorrect path"
  fi
done

VHSM_CNT_DIR=$VHSM_CNT_DIR$VHSM_CNT
mkdir -p /etc/vhsm
echo "$VHSM_CNT_DIR" > /etc/vhsm/vhsm.conf
#=================================================
if [ ! "$(vzlist | grep -o $VHSM_CNT)" ]; then
  vzctl create $VHSM_CNT --ostemplate debian-6.0-x86_64
  vzctl start $VHSM_CNT   
fi

#=================================================
cp /usr/lib/libprotobuf* $VHSM_CNT_DIR"/usr/lib/"
cp /usr/lib/libcrypto* $VHSM_CNT_DIR"/usr/lib/"
cp "/usr/bin/vhsm" $VHSM_CNT_DIR
/usr/bin/vhsm_admin i $VHSM_CNT_DIR"/data"

depmod
echo "vhsm_transport vhsm_veid=$VHSM_CNT" >> /etc/modules
modprobe vhsm_transport vhsm_veid=$VHSM_CNT

sed "s/^exit 0/\/vhsm\nexit 0/" $VHSM_CNT_DIR"/etc/rc.local"  >> /tmp/vhsm.temp
mv /tmp/vhsm.temp $VHSM_CNT_DIR"/etc/rc.local"

vzctl exec $VHSM_CNT ./vhsm &
