all: test_engine test_app

test_engine: main.c
	gcc -ggdb3 -c -fPIC main.c
	gcc -ggdb3 -shared -fPIC -o test_engine.so main.o -L/home/user/openssl_build_2/lib -lcrypto -lssl -ldl

test_app: test.c
	gcc -std=c99 -ggdb3 -L/home/user/openssl_build_2/lib -o test_app test.c -lcrypto -lssl -ldl

clean:
	rm -f *.o *.so test_app
