#!/bin/bash

not_correct=true
while $not_correct
do
  echo "Container id (DEFAULT: 412):"
  read VHSM_CNT
  if [ ! $VHSM_CNT ]; then
    VHSM_CNT=412  
  fi
  if [ $VHSM_CNT -gt 99 ]; then
    not_correct=false
  else
    echo "Incorrect container id"
  fi
done

not_correct=true
while $not_correct
do
  echo "Path to openvz containers (DEFAULT: /var/lib/vz/private/):"
  read VHSM_CNT_DIR
  if [ ! "$VHSM_CNT_DIR" ]; then
    VHSM_CNT_DIR="/var/lib/vz/private/"
  fi
  if [ -d $VHSM_CNT_DIR ]; then
    not_correct=false
  else
    echo "Incorrect path"
  fi
done

VHSM_CNT_DIR=$VHSM_CNT_DIR$VHSM_CNT
mkdir -p /etc/vhsm
echo "$VHSM_CNT_DIR" > /etc/vhsm/vhsm.conf
#=================================================
if [ ! "$(vzlist | grep -o $VHSM_CNT)" ]; then
  vzctl create $VHSM_CNT --ostemplate debian-6.0-x86_64
  vzctl start $VHSM_CNT   
fi

#=================================================
cp /usr/lib64/libprotobuf* $VHSM_CNT_DIR"/usr/lib/"
cp /usr/lib64/libcrypto* $VHSM_CNT_DIR"/usr/lib/"
cp "/usr/bin/vhsm" $VHSM_CNT_DIR

# CREATE DATABASE
if [ ! -e $VHSM_CNT_DIR"/data/keys.db" ]; then
    mkdir $VHSM_CNT_DIR"/data"
    sqlite3 $VHSM_CNT_DIR"/data/keys.db" "create table Users (
            UID                  INTEGER              primary key autoincrement,
            Name                 TEXT                 not null,
            AuthKey              BLOB                 not null,
            Salt                 BLOB                 not null,
            Iterations           INTEGER              not null )"
    sqlite3 $VHSM_CNT_DIR"/data/keys.db" "create unique index Users_PK on Users (UID)"
    sqlite3 $VHSM_CNT_DIR"/data/keys.db" "create table Keys (
            KeyID                TEXT                 not null,
            UID                  INTEGER              not null,
            Key                  BLOB                 not null,
            Purpose              INTEGER              not null,
            ImportDate           DATETIME             not null,
            CONSTRAINT Keys_PrimaryKey PRIMARY KEY(KeyID, UID),
            CONSTRAINT Keys_ForeignKey FOREIGN KEY(UID) REFERENCES Users(UID) ON DELETE RESTRICT ON UPDATE RESTRICT)"
    sqlite3 $VHSM_CNT_DIR"/data/keys.db" "create unique index Keys_PK on Keys (KeyID)"
    sqlite3 $VHSM_CNT_DIR"/data/keys.db" "create index UserKeys_FK on Keys (UID)"
fi

sed "s/^exit 0/\/vhsm\nexit 0/" $VHSM_CNT_DIR"/etc/rc.local"  >> /tmp/vhsm.temp
mv /tmp/vhsm.temp $VHSM_CNT_DIR"/etc/rc.local"

vzctl exec $VHSM_CNT ./vhsm &
